### ISSUE TITLE
About hand pose estimation

### ISSUE THREAD

**Issue by lzfff12** [postech-ami/FastMETRO#16]
When I ran the hand pose estimation code on other datasets, vertices_3d_loss did not converge.

**Comment by FastMETRO** [comment]
Hello,

The problem might be caused by incorrect preprocessing used for other datasets. Please refer to [METRO/metro/tools/ tsv_demo_freihand.py](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_freihand.py) for the preprocessing used for the FreiHAND dataset. Note that we assume input images are already cropped for the right hand to be centered in each image.

Thanks for your interest in our work!!

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.
