### ISSUE TITLE
About hand eval using freihand code

### ISSUE THREAD

**Issue by imabackstabber** [postech-ami/FastMETRO#8]
Hi, I followed the instruction in your [EXP.md](https://github.com/postech-ami/FastMETRO/blob/main/docs/Experiments.md), and run [Eval on Freihand](https://github.com/postech-ami/FastMETRO/blob/main/docs/Experiments.md#evaluation-on-freihand) using the same command as you give. But I got a json file which only contains `1980` predicted result, whereas the [Freihand evaluation code](https://github.com/lmb-freiburg/freihand) says there shall be `3960` result, which confuses me.
Is the `tsv` format test data doesn't match the eval set used by freihand? Or it is necessary to rewrite `pred.py` in [Freihand evaluation code](https://github.com/lmb-freiburg/freihand) to get things right?
Looking forward to your reply.

**Comment by imabackstabber** [comment]
UPDATE:
I tried rewrite `pred.py` mentioned above, by using the `./models/fastmetro_checkpoint/FastMETRO-L-H64_freihand_state_dict.bin` implemented in [demo code block](https://github.com/postech-ami/FastMETRO/blob/main/docs/Experiments.md#evaluation-on-freihand). However I just got **bad** result:
```bash
Evaluation 3D KP results:                                                                                                                                                            
auc=0.000, mean_kp3d_avg=147.53 cm                                                                                                                                                   
Evaluation 3D KP ALIGNED results:                                                                                                                                                    
auc=0.231, mean_kp3d_avg=4.41 cm

Evaluation 3D MESH results:
auc=0.000, mean_kp3d_avg=72.15 cm
Evaluation 3D MESH ALIGNED results:
auc=0.169, mean_kp3d_avg=5.01 cm

F-scores                                                                                                                                                                             
F@5.0mm = 0.000         F_aligned@5.0mm = 0.042                                                                                                                                      
F@15.0mm = 0.000        F_aligned@15.0mm = 0.230
```

I use the state_dict get from the [readme](https://github.com/postech-ami/FastMETRO#download), I don't train it again and just use it to eval, no test-time augmentation is added and the eval_batchsize is 1.
Am I doing wrong to the hyper-parameter? Or finetuning on freihand is needed? Please notify me if I'm wrong.
Looking forward to your reply.

**Comment by FastMETRO** [comment]
Hello,

Our code generates `pred.json` file which contains `3960` prediction results as stated in [FreiHAND](https://github.com/lmb-freiburg/freihand). 

We are not sure why you got a json file which only contained `1980` prediction results. `freihand/test.yaml` file has `3960` evaluation samples, and our code generates a prediction result for each sample.


Please check:
1) whether you correctly downloaded the FreiHAND dataset
2) `len(val_loader)` * `batch_size` == `3960` 

---

## Quantitative Evaluation Results
* obtained by using the released model checkpoint (`FastMETRO-L-H64_freihand_state_dict.bin`)

```
Evaluation 3D KP results:
auc=0.000, mean_kp3d_avg=71.50 cm
Evaluation 3D KP ALIGNED results:
auc=0.871, mean_kp3d_avg=0.65 cm

Evaluation 3D MESH results:
auc=0.000, mean_kp3d_avg=71.50 cm
Evaluation 3D MESH ALIGNED results:
auc=0.858, mean_kp3d_avg=0.71 cm

F-scores
F@5.0mm = 0.000         F_aligned@5.0mm = 0.687
F@15.0mm = 0.000        F_aligned@15.0mm = 0.983
```

- Note that only the aligned scores are considered because FastMETRO predicts relative coordinates, as in [METRO]( https://github.com/microsoft/MeshTransformer) and [Mesh Graphormer]( https://github.com/microsoft/MeshGraphormer). 
- There was no test-time augmentation.

## Qualitative Evaluation Results 
* obtained by using the released model checkpoint (`FastMETRO-L-H64_freihand_state_dict.bin`)

![freihand_example1](https://user-images.githubusercontent.com/109520798/206187925-4ba729d9-ce5b-4134-ae47-bca84d004cc5.jpg)
![freihand_example2](https://user-images.githubusercontent.com/109520798/206187953-7b292a69-899f-4eca-a641-2b78078d62e8.jpg)
![freihand_example3](https://user-images.githubusercontent.com/109520798/206187967-61da2bcb-7cea-40dd-a0a9-c48d5c67d63c.jpg)

**Comment by FastMETRO** [comment]
@imabackstabber 

### Please note that

1) Our code generates `pred.json` file which contains `3960` prediction results
2) There is no need to rewrite `pred.py` in [FreiHAND Evaluation Code]( https://github.com/lmb-freiburg/freihand)
3) The quantitative and qualitative evaluation results obtained by the pre-trained model (`FastMETRO-L-H64_freihand_state_dict.bin`) must be same as the above results
    - There was no test-time augmentation
    - There was no further fine-tuning

**Comment by FastMETRO** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by imabackstabber** [comment]
UPDATE:
The `1980` result is because I use command below:
```bash
python -m torch.distributed.launch --nproc_per_node=2 \
       src/tools/run_fastmetro_handmesh.py 
```
Note that `3960 = 1980 * 2`. This will lead to a single `pred.json` file which only contain `1980` elements because there are actually 2 processes launched by `torch.distributed.launch`, and one process(i.e. the slower one) will rewrite a `pred.json` and **override** one `pred.json` dumped by the former one.
To correct, just use command:
```bash
python src/tools/run_fastmetro_handmesh.py 
```
I suggest such modification could be updated in [exp.md](https://github.com/postech-ami/FastMETRO/blob/main/docs/Experiments.md)
p.s.: the former result I gained is probably due to wrong checkpoint. I re-download it, run the script, and get the same result as the paper showed.
Thanks for your help!

**Comment by FastMETRO** [comment]
Glad to hear that you got the same result as we obtained :)

Thanks for the detailed explanation regarding this issue! We updated [Experiments.md](https://github.com/postech-ami/FastMETRO/blob/main/docs/Experiments.md) to prevent such issue; a single process would generate `pred.json` file.
